language: node_js
services:
- mongodb
- redis-server
node_js:
- '0.10'
script: npm test
env:
  global:
  - PROVIDER_URL="http://localhost:8000"
  - GDRIVE_ANYFETCH_ID="fake-app-id"
  - GDRIVE_ANYFETCH_SECRET="fake-app-secret"
  - secure: lO1svqV4SdDilGedg6/6hZVUHmbq+2sN0WYoUB7rwi37QhM3rfs+cQMeSK3Ig21Pjo3TGjmYy3/p3f73SBwxrWBVBUe1SIULchgy6rcYrbiFWhJJv8Dg1KgijgaO9IIQtz3LQKGZK+rkc0W4DxdXF5frJYi1sXhT9DfYGxfU71o=
  - secure: heVWrCsL4fU7hOT9pqdiwdtWOcrbI1VV4Y2JhUEMJPrwNu+as1nv2G3/fgTKRao2BSXzonPah1Hi6ARnNuhWtHH1cCVqPI8KbQUqzt7+SaD4Ug5hj1MtTlUWMS7SULwNlGHhEMs1hkUd/tc7ZCIlWIaW0TRQDXBVWUi0LuZikEw=
  - secure: LcxnITdVWojxwGbAyJZosls8MqYyTnfT5vCE3SciK2b4bYbQfmEfSvZ2ZghvIhhcOmTTkQdh2Tildy/zhfNlAmii9aAxRL6F0ixtZsJV1IA7Ze0qkAaHV6/DZ8pRpub+fKA+7cyXPXSmELwvdL/i1GbxdhZXuuXpkq6D8sTtVVQ=
  - secure: A7zLLzKJoZEQaZlSgf6zBMfM4zGGx7PKm2G1Zlzj8vkjtSgni5Fsov5Cb030J/Y9L8urEsrrlnNr/2+ZwXLZuV++D5xM9yF/V/fxAnFFjwcJUOGloMfO+o4utTN1isE+/ijwCTzeQ2VaDgvM9wOoYH/o402hgrNGlhrcy+T8zJg=
